[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

remappings=[
    "@openzeppelin/contracts=./node_modules/@openzeppelin/contracts",
    "@openzeppelin/contracts-upgradeable=./node_modules/@openzeppelin/contracts-upgradeable",
    "@chainlink/contracts=./node_modules/@chainlink/contracts",
]

[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"

[etherscan]
testnet = { key = "${ETHERSCAN_API_KEY}" }